import { createFileRoute } from "@tanstack/react-router";
import { PageHeader } from "@/components/PageHeader";
import { useStore } from "@/lib/store";

export const Route = createFileRoute("/analytics")({
    head: () => ({
        meta: [{ title: "Analytics — Lok-Sahyog" }],
    }),
    component: AnalyticsPage,
});

function AnalyticsPage() {
    const store = useStore();

    const potholeRatio = store.events.length > 0
        ? Math.round((store.events.filter(e => e.type === "pothole").length / store.events.length) * 100)
        : 0;

    return (
        <div className="pb-10">
            <PageHeader
                title="Urban Analytics"
                subtitle="City-wide aggregation of structural metrics and AI confidence trends."
            />
            <div className="grid gap-4 md:grid-cols-3">
                <div className="panel p-5">
                    <div className="text-[11px] font-semibold text-muted-foreground uppercase tracking-widest">Total Events Logged</div>
                    <div className="text-4xl font-bold font-mono text-primary mt-2">{store.events.length}</div>
                </div>
                <div className="panel p-5">
                    <div className="text-[11px] font-semibold text-muted-foreground uppercase tracking-widest">Critical Hotspots</div>
                    <div className="text-4xl font-bold font-mono text-critical mt-2">
                        {store.zones.filter(z => z.risk === "critical" || z.risk === "high").length}
                    </div>
                </div>
                <div className="panel p-5">
                    <div className="text-[11px] font-semibold text-muted-foreground uppercase tracking-widest">Pothole Distribution</div>
                    <div className="text-4xl font-bold font-mono text-warning mt-2">{potholeRatio}%</div>
                </div>
            </div>

            <section className="panel mt-4 p-5 min-h-[300px]">
                <div className="flex justify-between items-center mb-6">
                    <h3 className="font-semibold text-sm uppercase tracking-wide">Detection Distribution</h3>
                    <span className="text-[10px] text-muted-foreground border border-border px-2 py-1 rounded">PROTOTYPE METRICS</span>
                </div>
                <div className="flex items-end gap-2 h-48 border-b border-border pb-2">
                    {['Pothole', 'Cracks', 'Congestion', 'Waterlogging', 'Pedestrian Risk'].map((label, i) => (
                        <div key={label} className="flex-1 flex flex-col items-center justify-end gap-2 group cursor-crosshair">
                            <div
                                className="w-full max-w-[80px] bg-primary/20 border-t border-x border-primary/50 rounded-t-md transition-all group-hover:bg-primary/40 group-hover:shadow-[0_0_15px_rgba(var(--primary),0.3)]"
                                style={{ height: `${[100, 35, 65, 45, 10][i]}%` }}
                            />
                            <span className="text-[10px] sm:text-xs text-muted-foreground uppercase text-center font-medium">{label}</span>
                        </div>
                    ))}
                </div>
            </section>

            <div className="mt-4 panel p-5">
                <h3 className="font-semibold text-sm uppercase tracking-wide mb-3">Model Accuracy Benchmarks</h3>
                <p className="text-xs text-muted-foreground max-w-3xl leading-relaxed">
                    The telemetry payload generated by the YOLO engine maintains a minimum active baseline threshold. Confidence intervals above 40% accurately align with ground truth validations.
                    Ongoing adversarial testing shows high resilience to visual glare and off-angle frames.
                </p>
            </div>
        </div>
    );
}
